---
- name: Install Ansible Tower
  hosts: tower
  become_user: tower
  become: yes

  tasks:    
    - name: Update apt-get cache
      apt: >
        update_cache=yes
        cache_valid_time=3600
      become_user: root
      become: yes

    - name: Update all packages to the latest version
      apt: > 
        upgrade=yes
      become_user: root
      become: yes

    - name: set timezone to Europe/Amsterdam
      timezone:
        name: Europe/Amsterdam
      become_user: root
      become: yes

    - name: wolfram-engine
      apt: 
        name: wolfram-engine
        state: absent
      become_user: root
      become: yes
        
    - name: tar xvzf ansible-tower-setup-latest.tar.gz
      unarchive:
        src: ./ansible-tower-setup-latest.tar.gz        
        dest: /tmp
        remote_src: false

    - name: copy config
      copy:
        src: ./inventory
        dest: /tmp/ansible-tower-setup-3.1.3/inventory

    - name: Setup Ansible Tower
      command: /tmp/ansible-tower-setup-3.1.3/setup.sh
      args:
        chdir: /tmp/ansible-tower-setup-3.1.3
      become_user: root
      become: yes
